### ISSUE TITLE
is not working?

### ISSUE THREAD

**Issue by 9acca9** [blackoders/drinkly#5]
Hi. Dont work any command for me.
This is abandoned?
Thanks.

**Comment by blackode** [comment]
Hi, @9acca9 
The code works, you can host it in your server.

We are currently not hosting this anymore. So, we opensource the code. So, people can host it on their servers.

Sorry for that and we let you know once again when we host this code in our server in future.

Thanks for showing interest.

**Comment by blackode** [comment]
I'm closing this issue for now. 
Feel free to open the issue again if you wish to.
